### ISSUE TITLE
Attachment timestamp required on Mainnet

### ISSUE THREAD

**Issue by wusyong** [yillkid/iota-swarm-node#15]
Unlike devnet, transaction without `attachment_timestamp` won't be confirm on mainnet even with recent hercules tip-sel algo. I can provide more results if needed. As for now, here's side by side comparison:

- Mainnet: [With timestamp](https://thetangle.org/transaction/JDIRX9FQ9OI9JREJNGORVDRLJDHANBEBKVELUVEOSVLYLYAB9DFXGSI9EBMWTKJZFXIYMQXNVYMFZ9999) / [Without timestamp](https://thetangle.org/transaction/DPIAZICTVOEX9OCAJQZQJSZWHSFZFOWPTUVDYJDJJYBYLVIRMUTMJTG9SOU9ZCZRY9VYWLJHNQRFZ9999)
- Devnet: [With timestamp](https://devnet.thetangle.org/transaction/C9EEPZ9BSCDVORKIPYFNJMHRSRCYFSCTVFAEHDEU9ZRKZHTVIOALKGT9GEEBXFXXFESCMQEMQTIE99999) / [Without timestamp](https://devnet.thetangle.org/transaction/FLL9RZIRRANZAAVIKNCTJPFNKJGBKVYTKONLX9LMMKWXDILGJJDDVREE9B9NMCSIJJYABWTOPWRMA9999)

**Comment by jserv** [comment]
@wusyong, can you propose the expected modifications against existing codebase?

**Comment by wusyong** [comment]
Here is the modification. `time_start_pow` is moved inside the loop since every transactions in same bundle are expected to have different attachment timestamp. `timestamp_lower_bound` and `timestamp_upper_bound` are optional,  even api call `attachToTangle` from IRI assign 0 and max value separately. So they are assigned same values here. Should I create a pull request?

### Proposed method:
https://github.com/wusyong/iota-swarm-node/blob/2f2f30e3ecadbebbacb3dfe1eeef7da21ce2effb/swarm_node.py#L129-L138
