### ISSUE TITLE
Bundle inconsistency if it has multiple transactions

### ISSUE THREAD

**Issue by wusyong** [yillkid/iota-swarm-node#29]
There is no problem preparing 0 value transfer which bundle only has one transaction. However, if we send a value transfer, the bundle would be inconsistent since all transactions' trunk/branch transactions are point to same tips.

### Expected behavior:
![](https://i.imgur.com/V7xHEMJ.png)

### Actual behavior:
![](https://i.imgur.com/42Zs9mM.png)

**Comment by jserv** [comment]
Loop @KevinKu
